site_name: "GFF Schema (DRAFT, pre-alpha)"
theme:
  name: readthedocs
  analytics:
    gtag: G-2SYBSJVZ23
nav:
  - Home: home.md
  - Index: index.md
  - Credits: credits.md
repo_url: https://github.com/biodatamodels/gff-schema
site_url: https://biodatamodels.github.io/gff-schema/
